import axios from 'axios';
import AsyncStorage from '@react-native-async-storage/async-storage';

// In compiled APKs, Expo sometimes loses env variables unless passed through EAS secrets.
// Adding the real Cloud Run URL as the explicit fallback ensures we don't fall back to localhost on device.
const API_URL = process.env.EXPO_PUBLIC_API_URL || process.env.API_URL || 'https://wardrobe-backend-e5uidowr6a-ew.a.run.app/api';

// Validate API_URL format
try {
  const url = new URL(API_URL);
  if (!['http:', 'https:'].includes(url.protocol)) {
    throw new Error(`Invalid API_URL protocol: ${url.protocol}. Must be http: or https:`);
  }
} catch (error) {
  console.error('❌ CRITICAL: Invalid API_URL format:', API_URL);
  throw new Error(`Invalid API_URL: ${API_URL}. Must be a valid HTTP/HTTPS URL.`);
}

console.log('📡 API Base URL:', API_URL);

const api = axios.create({
  baseURL: API_URL,
  timeout: 30000,
  headers: {
    'Content-Type': 'application/json',
  },
});

api.interceptors.request.use(
  async (config) => {
    const token = await AsyncStorage.getItem('authToken');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    console.log('🔵 API Request:', {
      method: config.method?.toUpperCase(),
      url: `${config.baseURL || ''}${config.url || ''}`,
      headers: config.headers,
      hasData: !!config.data,
    });
    return config;
  },
  (error) => Promise.reject(error)
);

api.interceptors.response.use(
  (response) => {
    console.log('🟢 API Response:', {
      status: response.status,
      url: response.config.url,
    });
    return response;
  },
  async (error) => {
    console.error('🔴 API Error:', {
      status: error.response?.status,
      statusText: error.response?.statusText,
      url: error.config?.url,
      method: error.config?.method,
      fullURL: `${error.config?.baseURL || ''}${error.config?.url || ''}`,
      data: error.response?.data,
      message: error.message,
    });
    // Only clear tokens on 401 (Unauthorized/expired token)
    // 403 means Forbidden (insufficient permissions), not invalid token
    if (error.response?.status === 401) {
      await AsyncStorage.removeItem('authToken');
      await AsyncStorage.removeItem('user');
    }
    return Promise.reject(error);
  }
);

export const authAPI = {
  register: (data: { email: string; password: string; username?: string; full_name?: string }) =>
    api.post('/auth/register', data),
  login: (data: { email: string; password: string }) =>
    api.post('/auth/login', data),
  getProfile: () =>
    api.get('/auth/profile'),
};

export const wardrobeAPI = {
  analyzeImage: async (formData: FormData) => {
    console.log('📤 Uploading to /wardrobe/analyze endpoint');
    return api.post('/wardrobe/analyze', formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
        'Accept': 'application/json',
      },
    });
  },
  addItem: async (formData: FormData) => {
    console.log('📤 Uploading to /wardrobe endpoint');
    // In React Native, do NOT manually set Content-Type for FormData
    // It strips the boundary string, causing the backend to fail parsing
    return api.post('/wardrobe', formData, {
      headers: {
        'Accept': 'application/json',
        // Content-Type is auto-generated by Axios with the boundary
      },
      transformRequest: (data) => data, // crucial for React Native FormData
    });
  },
  getItems: (params?: { category?: string; season?: string; sort_by?: string; order?: string }) =>
    api.get('/wardrobe', { params }),
  getUnusedItems: (days?: number) =>
    api.get('/wardrobe/unused', { params: { days } }),
  updateItem: (id: number, data: any) =>
    api.put(`/wardrobe/${id}`, data),
  deleteItem: (id: number) =>
    api.delete(`/wardrobe/${id}`),
  logWear: (id: number, data: { worn_date?: string; weather?: string; occasion?: string; notes?: string }) =>
    api.post(`/wardrobe/${id}/wear`, data),
};

export const outfitAPI = {
  generateAI: (data: { occasion?: string; weather?: string; season?: string }) =>
    api.post('/outfits/generate', data),
  getOutfits: (params?: { is_favorite?: boolean }) =>
    api.get('/outfits', { params }),
  createManual: (data: { title?: string; description?: string; occasion?: string; season?: string; item_ids: number[] }) =>
    api.post('/outfits', data),
  toggleFavorite: (id: number) =>
    api.post(`/outfits/${id}/favorite`),
};

// Phase 2 Social Feed API (v1 endpoints)
export const socialFeedAPI = {
  // Profile
  createProfile: (data: { username: string; displayName?: string; bio?: string; visibility?: string; profilePhotoUrl?: string }) =>
    api.post('/social/v1/profile', data),
  getProfile: (username?: string) =>
    username ? api.get(`/social/v1/profile/${username}`) : api.get('/social/v1/profile'),
  updateProfile: (data: { displayName?: string; bio?: string; visibility?: string; profilePhotoUrl?: string }) =>
    api.patch('/social/v1/profile', data),
  deleteProfile: () =>
    api.delete('/social/v1/profile'),
  searchUsers: (query: string, limit?: number) =>
    api.get('/social/v1/search', { params: { q: query, limit } }),
  
  // Follow
  follow: (targetUserId: number) =>
    api.post('/social/v1/follows', { targetUserId }),
  unfollow: (targetUserId: number) =>
    api.delete(`/social/v1/follows/${targetUserId}`),
  getFollowers: (params?: { userId?: number; cursor?: string; limit?: number }) =>
    api.get('/social/v1/follows/followers', { params }),
  getFollowing: (params?: { userId?: number; cursor?: string; limit?: number }) =>
    api.get('/social/v1/follows/following', { params }),
  
  // Posts
  createPost: (formData: FormData) =>
    api.post('/social/v1/posts', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
  getPost: (postId: number) =>
    api.get(`/social/v1/posts/${postId}`),
  getUserPosts: (params?: { userId?: number; cursor?: string; limit?: number }) =>
    api.get('/social/v1/posts', { params }),
  updatePost: (postId: number, data: { caption?: string; visibility?: string }) =>
    api.patch(`/social/v1/posts/${postId}`, data),
  deletePost: (postId: number) =>
    api.delete(`/social/v1/posts/${postId}`),
  
  // Feed
  getFeed: (params?: { cursor?: string; limit?: number }) =>
    api.get('/social/v1/feed', { params }),
  
  // Engagement
  likePost: (postId: number) =>
    api.post('/social/v1/likes', { postId }),
  unlikePost: (postId: number) =>
    api.delete(`/social/v1/likes/${postId}`),
  savePost: (postId: number) =>
    api.post('/social/v1/saves', { postId }),
  unsavePost: (postId: number) =>
    api.delete(`/social/v1/saves/${postId}`),
  getSavedPosts: (params?: { cursor?: string; limit?: number }) =>
    api.get('/social/v1/saves', { params }),
    
  // Comments
  addComment: (postId: number, content: string) =>
    api.post(`/social/v1/posts/${postId}/comments`, { content }),
  getComments: (postId: number, params?: { cursor?: string; limit?: number }) =>
    api.get(`/social/v1/posts/${postId}/comments`, { params }),
  deleteComment: (commentId: number) =>
    api.delete(`/social/v1/comments/${commentId}`),
    
  // Notifications
  getNotifications: (params?: { cursor?: string; limit?: number }) =>
    api.get('/social/v1/notifications', { params }),
  getUnreadNotificationCount: () =>
    api.get('/social/v1/notifications/unread-count'),
  markNotificationsRead: () =>
    api.post('/social/v1/notifications/mark-read'),
    
  // Trust & Safety
  blockUser: (targetUserId: number) =>
    api.post('/social/v1/blocks', { targetUserId }),
  unblockUser: (targetUserId: number) =>
    api.delete(`/social/v1/blocks/${targetUserId}`),
  reportContent: (data: { targetType: 'post' | 'user' | 'comment'; targetId: number; reason: string; details?: string }) =>
    api.post('/social/v1/reports', data),
};

export const socialAPI = {
  createReel: (formData: FormData) =>
    api.post('/social/reels', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
  getFeed: (params?: { page?: number; limit?: number }) =>
    api.get('/social/feed', { params }),
  likeReel: (id: number) =>
    api.post(`/social/reels/${id}/like`),
  commentOnReel: (id: number, content: string) =>
    api.post(`/social/reels/${id}/comment`, { content }),
  followUser: (userId: number) =>
    api.post(`/social/users/${userId}/follow`),
  getFollowers: (userId?: number) =>
    api.get(`/social/users/${userId || 'me'}/followers`),
  getFollowing: (userId?: number) =>
    api.get(`/social/users/${userId || 'me'}/following`),
};

export const contextAPI = {
  getMoods: () => api.get('/context/moods'),
  getEventTypes: () => api.get('/context/event-types'),
  updateProfile: (data: { city?: string; location_mode?: string; primary_language?: string; preferred_currency?: string; notification_enabled?: boolean; preferred_brands?: string; preferred_colors?: string }) =>
    api.put('/context/profile', data),
  updateConsent: (data: { personalised_ads_enabled?: boolean; contextual_ads_only?: boolean; community_visibility_mode?: string }) =>
    api.put('/context/consent', data),
  getConsent: () => api.get('/context/consent'),
  toggleFavorite: (itemId: number) => api.post(`/context/wardrobe/${itemId}/favorite`),
  toggleLocked: (itemId: number) => api.post(`/context/wardrobe/${itemId}/lock`),
};

export const dailyAPI = {
  generate: (data: { city?: string; destination_city?: string; mood_id?: number; event_type_id?: number; count?: number }) =>
    api.post('/daily/generate', data),
  approve: (outfitId: number) => api.post(`/daily/${outfitId}/approve`),
  swap: (outfitId: number, itemIdToSwap: number) =>
    api.post(`/daily/${outfitId}/swap`, { item_id_to_swap: itemIdToSwap }),
  regenerate: (outfitId: number) => api.post(`/daily/${outfitId}/regenerate`),
  save: (outfitId: number) => api.post(`/daily/${outfitId}/save`),
};

export const insightsAPI = {
  getWardrobe: () => api.get('/insights/wardrobe'),
  getHistory: (params?: { limit?: number; offset?: number }) =>
    api.get('/insights/history', { params }),
};

export const analyticsAPI = {
  trackEvent: (eventType: string, payload?: any) =>
    api.post('/analytics/track', { event_type: eventType, payload }),
};

export default api;
